security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
        main_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: home
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
            provider: main_provider
            
    access_control:
        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/info, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cgu, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pwd, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/character, roles: ROLE_USER }
        - { path: ^/preferences, roles: ROLE_USER }
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/, roles: ROLE_VERIFIED }
        