security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
    providers:
        in_memory: { memory: ~ }
        main_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            http_basic: ~
            provider: main_provider
            
    access_control:
        - { path: ^/$, roles: [] }
        - { path: ^/subscribe, roles: [] }
        - { path: ^/, roles: ROLE_USER }
        